name: Tests, Lints and Deploy

on: push # Runs only on push event for any branche

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci

      - name: Lints
        run: npm run lint
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci

      - name: Test
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: [lints, tests]
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Runs the docker compose
        run: docker compose up -d

      - name: Success
        run: echo "Deployed successfully..."

      - name: Stop the docker compose
        run: docker compose down
